### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by skymeyer** [robrichards/xmlseclibs#104]
Currently https://github.com/onelogin/php-saml is including ```xmlseclibs``` manually instead of relying on a composer dependency. As per https://github.com/onelogin/php-saml/issues/81 they want to switch composer. Can we have a new release with the latest fixes from master of ```xmlseclibs``` as soon as possible ?

Thanks

**Comment by siwinski** [comment]
:+1: downstream packaging (Fedora/EPEL) would love both 2.0.1 and 1.4.2 official releases

**Comment by patkar** [comment]
Any update on this?

**Comment by robrichards** [comment]
Will have a release this week.

**Comment by Overtonesinger** [comment]
Dear Rob,

        I have an interesting issue with a webservice.
        It has a WSDL URL  *such*  that it causes the PHP  SoapClient class
__construct()    to FAIL in finding the XSD imports  despite they are in
place!

        Could Your library address this bug?

         I am certain that many many users must have stumbled upon this
and would be happy if the lib could help them to overcome this nasty BUG!
        ...  Now I am desperate -  having to REWRITE the low-level api
calls in extended SoapClient object to repair the place where it
ERRONEously looks for XSD schema.....

         This is crazy!! ,  but seems I will have to do it this way
  :-( hacking PHP5.6.24 core.. :)))

Would You help me with advice , please?
        Are You interested in details?

Thanx.

*Namaste*
Filip

Dne 6. 9. 2016 19:00 napsal uživatel "Rob Richards" <
notifications@github.com>:

Will have a release this week.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/robrichards/xmlseclibs/issues/104#issuecomment-245017423>,
or mute the thread

**Comment by robrichards** [comment]
I have created both a 2.0.1 and 1.4.2 release. 
@Overtonesinger unrelated to this thread so you should create a new issue. In any case can you send me the WSDL so I can take a look at it?
