### ISSUE TITLE
Convert classes to PSR-0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [robrichards/xmlseclibs#14]
```
PSR-0 is the new way of structuring classes into include files. See 
https://gist.github.com/1234504. Using PSR-0 will make xmlseclibs easily 
embeddable in any system that uses a PSR-0-compatible class loader. Using 
namespaces prevents collisions with other projects.
```

Original issue reported on code.google.com by `b...@mynameisbart.com` on 28 Oct 2012 at 4:52

**Comment by jaimeperez** [comment]
@robrichards, I can provide a pull request modifying the code so that it adheres to the PSR-0 coding standard, separating classes to their own files. Would you be willing to incorporate such a change?

At some point I also think we should add namespaces, but maybe we can take one step at a time, and for now just split the file into smaller classes. What do you think?

**Comment by Maks3w** [comment]
I think both things can be done at the sametime

**Comment by Maks3w** [comment]
@robrichards I suggest to prioritize this. Manage the monolotic PHP file it's a nightmare

**Comment by jaimeperez** [comment]
Namespaces are slightly more complicated, because then you are forcing those using PHP versions older than 5.3 to upgrade, which at this point could be painful (though pretty much recommended). I don't know how many people is using PHP 5.2, but I prefer to leave that decision to Rob. If he's fine with it, I'm totally in :smile:

**Comment by BernardoSilva** [comment]
@jaimeperez Why not create a tag before adding namespaces and bump the major release number after adding namespaces? :) 
This way people ca still use older version `~1.3` and if they want to update, just change the version number to use `~2.0`

**Comment by jaimeperez** [comment]
Actually what I'm doing right now, after splitting the classes up into separate files, is to bump the version number to 1.4. That itself is a change big enough to bump the minor version, since we are not really patching a bug, but still nothing should break in the API (people should still be able to use the library if they use composer in the same way they use it today).

If @robrichards agrees to start using namespaces, I'd then bump the version number to 2.0, definitely :+1:

**Comment by robrichards** [comment]
Let me think it through a little. I have local code which made it PSR-0 compliant which we could make a 1.4 branch for that (as I do need to keep a branch alive that is 100% BC from existing) while having 2.0 become the namespace version. I have been debating wether to drop the PHP 5.1 support which this may help make that decision easier.

**Comment by Maks3w** [comment]
1) The correct version for PSR0 or namespace is 2.0. Both are bc breaks.

2) My rule of thumb is not support versions the provider does not support too. In this case the minimum  version should be 5.5

**Comment by siwinski** [comment]
> 2) My rule of thumb is not support versions the provider does not support too. In this case the minimum version should be 5.5

I subscribed to this issue because I package this library downstream for [Fedora](https://getfedora.org/) and [EPEL](https://fedoraproject.org/wiki/EPEL) (which is used by RHEL and its' [derivatives](http://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux_derivatives#List_of_Red_Hat_Enterprise_Linux_derivatives)).  I'm hoping that common/enterprise OSes that provide and support PHP will be taken into consideration when making the minimum PHP version decision.  RHEL 6 & 7 are used by many enterprises and benefit from libraries such as this so hopefully this library could continue to be used/supported on these OSes. RHEL 6 packages and supports PHP 5.3.3 and RHEL 7 packages and supports PHP 5.4.16.  RHEL 7 is relatively new and many enterprises have not even upgraded their RHEL 6 systems to 7 yet.

**Comment by robrichards** [comment]
@siwinski Im only considering dropping support for PHP < 5.2 at this time as it would allow me to drop some code that exists strictly for that

**Comment by Maks3w** [comment]
Ok then we can do another thing.

Seems @robrichards knows people who need the actual support. You could declare 1.3 as a LTS version which will receive only security fixes and high critical bugs and then open a new branch (v2) for work only with recent versions and technologies

This is, we start to develop new features and  @robrichards could backport the changes to v1.3

**Comment by robrichards** [comment]
That's currently how I'm thinking tho wondering if I want to have a 1.4 branch as well where I would drop at least versions < 5.2 if not also 5.2. Would backport new/fixed functionality to the 1.4 branch, not just security /critical.

**Comment by jaimeperez** [comment]
Hi!

On 27 May 2015, at 23:31, Maks3w <notifications@github.com<mailto:notifications@github.com>> wrote:


1) The correct version for PSR0 or namespace is 2.0. Both are bc breaks.

Not really, PSR-0 can be achieved in a fully backwards-compatible way. Namespaces can't.


2) My rule of thumb is not support versions the provider does not support too. In this case the minimum version should be 5.5

Unfortunately life is not that easy. There's quite a lot of people out there using 5.2 or older. Still, that's already no longer supported, so I would consider 5.3 a reasonable "minimum" version.

**Comment by jaimeperez** [comment]
> On 28 May 2015, at 22:37, Rob Richards <notifications@github.com> wrote:
> That's currently how I'm thinking tho wondering if I want to have a 1.4 branch as well where I would drop at least versions < 5.2 if not also 5.2. Would backport new/fixed functionality to the 1.4 branch, not just security /critical.

I'd say removing support fir PHP <= 5.2 is quite reasonable. I mean, even 5.3 is close to being unsupported, though that one we need to support for cases as the one Shawn is describing, anyway.

On the other hand, backporting everything (not just security) to a legacy 1.4 branch would be bad, I think. It'll be a pain for you to manage if you decide to backport new features on your own, and it'll be bad for the library if on the other hand you require people to provide implementations for both "current" and "legacy", as that'll refrain people from contributing.

**Comment by Maks3w** [comment]
5.3 is EOL and 5.4 is deprecated (EOL on September)

**Comment by thijskh** [comment]
Major distributions, both commercial and non-commercial, will be providing continued support for 5.3 and 5.4 for years to come. Removing support for < 5.3 seems reasonable to me aswell.

**Comment by robrichards** [comment]
@Maks3w @thijskh That's what I'm basing my support on. I know of corporate installs still running RedHat and CentOS 5, which is PHP 5.3 based, and an EOL of 2017.

@jaimeperez I wouldn't be requiring people to provide implementations for both. If it's possible to write it so it's compatible, I will highly suggest it (or I may suggest an alternative change). I plan on back porting only changes I think would be beneficial or needed in the 1.4 branch. I'm not looking at or requiring a 1:1 functional equivalent between 1.4 and 2.0 to be clear.

**Comment by robrichards** [comment]
@Maks3w @jaimeperez @siwinski @thijskh I have added PSR-0 support to the 1.4 branch. Currently 1.4 and master have also dropped support for PHP < 5.2. I plan on leaving the 1.4 branch as PSR-0 while using master (2.x) for adding namespace support. Please take a look at the 1.4 branch and let me know if there is anything else anyone wants to include or modify before I create the release off it

**Comment by Maks3w** [comment]
Let me a couple of days before give my feedback.

By the way please add the following in `composer.json` above of "suggest" option (you can place whenever you like but I prefer require, require-dev, suggest order).

```
"require": {
    "php": ">= 5.2"
 },
```

Execute `composer validate` for to validate the syntax

**Comment by Maks3w** [comment]
Also I think because there is no namespace is better to use autoload class option rather PSR-0

Finally if you don't want to use PHP 5.3 namespaces then you can use PEAR style class names, this style is compatible with PSR-0

```php
// src/VendorName/Component/Foo.php

class VendorName_Component_Foo {
}
```

You could use `RobRichards_Xmlseclibs_XMLSecEnc`

**Comment by thijskh** [comment]
One detail: the README should be updated to mention the increased PHP requirement.

**Comment by robrichards** [comment]
@thijskh Done. Thanks

**Comment by Maks3w** [comment]
https://github.com/robrichards/xmlseclibs/pull/52 Use classmap instead PSR-0

Hope to drop support for 5.2 soon for implement namespaces

**Comment by robrichards** [comment]
That is where master is going with the 2.x branch. 1.4 will retain 5.2 support while 2.x will be for namespaces. That's why master has been left as is so far. Haven't had the time yet to get to it.

**Comment by Maks3w** [comment]
Then for v2 we can do namespaces and PSR-4 at the same time.

We had to do 2 objectives with the project:

- Composer compliance
- Split monolithic file.

Both things are achieved and there is no reason for change more things in the source files structure.


The autoload key in composer.json is BC safe. i,e does not matter if you change from PSR-0 to classmap, to PSR-4 or viceversa.

It's BC Break to change class names.

**Comment by robrichards** [comment]
closing this out

**Comment by siwinski** [comment]
@robrichards I create a snapshot RPM of 1.4 and have not found any issues or have been reported any issues.  THANKS!
