### ISSUE TITLE
Remove dependency on mcrypt

### ISSUE THREAD

**Issue by cweagans** [robrichards/xmlseclibs#55]
See http://thefsb.tumblr.com/post/110639027905/custodians-of-php-vote-to-keep-a-crypto-lib for some details.

The openssl extension supports everything mcrypt supports and more. Would migrating to openssl be an option?

**Comment by robrichards** [comment]
I'll look into it, but if it simplifies dependancies I'm all for it.

**Comment by gfaust-qb** [comment]
I strongly agree to @cweagans, @thijskh and @jaimeperez to remove this deprecated dependency. 
The openssl extension supports all needed functionality, is supported, not removed in PHP7 and much faster than the mycrypt extension.

**Comment by sergejgoldstein** [comment]
We're trying to get simplesaml 1.13 running on RedHat Linux 7, which does not support mcrypt.   A non-mcrypt version of xmlsecllibs would be very helpful.

**Comment by cweagans** [comment]
For anyone interested, I'm working on a polyfill for mcrypt, which is basically just a lib that provides the same functions, but instead of being backed directly by mcrypt, they're backed by phpseclib and in turn, openssl. You can find that at https://github.com/cweagans/mcrypt-polyfill. It's not on Packagist yet, as it's very far from complete. If you want to help, https://github.com/cweagans/mcrypt-polyfill/issues is a good place to start. A lot of the work right now is porting tests from php-src (it's pretty easy, since the tests are actually written in PHP), and then wiring up the mcrypt functions appropriately.

**Comment by gfaust-qb** [comment]
@cweagans Nice to hear! I just did some refactorings and replaced Encryption by pure openssl and decryption by phpseclib/phpseclib. (I tried to do the padding in case of PHP 5.3 myself but PHPSeclib was a faster solution.) 
Also I have to say that my solution is just a replacement, not supporting all Algorithms and Modes supported by PHPSeclib.
If someone wants to have a look: https://github.com/gfaust-qb/xmlseclibs/tree/Specified_Exception
Next Step is to remove all calls of openssl by PHPSeclib.
I know that this is not the prefered solution for @robrichards because it is not as fast as a native solution could be - but it supports a lot of different environments.

**Comment by cweagans** [comment]
Calling openssl is fine. It works well, and I wouldn't recommend stripping it out. Until the Sodium bindings for PHP are more widespread, OpenSSL is sadly the best thing available. Native PHP encryption is *slow* - nearly unusable if you're doing something complicated. I may be misunderstanding, though.

**Comment by gfaust-qb** [comment]
@cweagans I understand what you mean - and that you are not implementing it in pure PHP!
Using PHPSeclib or another Wrapper is not the preferred Solution of @robrichards - but mine ;)
My Solution is just to remove the Dependencies from PHP-Extensions from xmlseclibs - Yours (that is what I understood) also should provide Support for the other Algorithms & Modes.

**Comment by robrichards** [comment]
Released via version 3.0.0
