### ISSUE TITLE
My proposition to fix CSharp problem with different in DigestValue and SignatureValue

### ISSUE THREAD

**Issue by lukaszbulzacki** [robrichards/xmlseclibs#83]
Hi,

I found solution to problem with different **DigestValue** and **SignatureValue** in **php** and **c#**. It is not tested in many different scenarios but it seams to working.

#### It require 2 things.

**First** is change in file `robrichards/xmlseclibs/src/XMLSecurityDSig.php` in constructor (look for line with comment "CHANGE PROPOSITION" in code below, I added this line).
```php
    public function __construct($prefix='ds')
    {
        $template = self::BASE_TEMPLATE;
        if (! empty($prefix)) {
            $this->prefix = $prefix.':';
            $search = array("<S", "</S", "xmlns=");
            $replace = array("<$prefix:S", "</$prefix:S", "xmlns:$prefix=");
            $template = str_replace($search, $replace, $template);
        }
        $sigdoc = new DOMDocument();
        $sigdoc->preserveWhiteSpace = false; // CHANGE PROPOSITION
        $sigdoc->loadXML($template);
        $this->sigNode = $sigdoc->documentElement;
    }
```

**Second** is specific usage of library:
* message document should have set flag `DOMDocument::preserveWhiteSpace = false`
* `XMLSecurityDSig::__constructor` should have set argument to `null`
```php
 $msgToSign = <<<XML
<?xml version="1.0" encoding="utf-8"?>
<root>
   <message>
      ...
   </message>
</root>
XML;
 $docToSign = new \DOMDocument();
 $docToSign->preserveWhiteSpace = false;
 $docToSign->loadXML($msgToSign);

 $dsig = new XMLSecurityDSig(null);
```
My settings:
* php 5.6

**Comment by robrichards** [comment]
Can you try with latest from master as this may already be fixed for your case? If you are still running into the issue please send me a full working example in C# as I do run intro tests locally against WSE based applications.

**Comment by jcav2** [comment]
It require one more thing and work like a charm:

See answer #77

You need also change:

`$objDSig->sign($objKey);`

to

`$objDSig->sign($objKey, $ParentNode);`

The change changes canonicalization because C14N return different result if Signature node is allready part of main doc vs. Signature node is added after signing is complete. 

$ParentNode would be: $docToSign->documentElement

    $docToSign = new DOMDocument('1.0');
    $docToSign->preserveWhiteSpace = true;
    $docToSign->formatOutput = false;
    $docToSign->encoding = 'UTF-8';
    
    try {
        $docToSign->loadXML($yourData);
        $docToSign->preserveWhiteSpace = true;
        $docToSign->formatOutput = false;
        $docToSign->encoding = 'UTF-8';
    } catch (Exception $e) {
        echo "Error loading xml : " . $e->getTraceAsString();
        return "ERROR";
    }

and if you want to avoid this line:
`$sigdoc->preserveWhiteSpace = false; // CHANGE PROPOSITION`

you can set a base template and call it instead of the others templates:

`const BASE_TEMPLATE_CSHARP = '<Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><SignatureMethod /></SignedInfo></Signature>';`

**Comment by lukaszbulzacki** [comment]
OK. Seems good. Thanks.
